# 3 Exploratory data analysis

```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/setup.R"))
```

## 3.1 Monthly Real Retail Turnover Index EDA

<br>

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">

little explanation of what we're show to see with the data

</div>

<br>


```{r, fig.align='center'}
ts %>% autoplot(tot)
```

```{r, fig.align='center'}
ts %>% ACF(tot) %>% autoplot()
ts %>% features(tot, feat_acf)
```

```{r, fig.align='center'}
ts %>% gg_lag(tot, geom = "point")
```

```{r, fig.align='center'}
# Classical decomposition
# Classical decomposition additive
ts %>% 
  model(classical_decomposition(tot, type = "additive")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
# Classical decomposition multiplicative
ts %>%
  model(classical_decomposition(tot, type = "multiplicative")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
```

```{r, fig.align='center'}
# Let's check the seasonality:

ts %>% gg_season(tot)

# We can notice from the season plot that December is the month with the highest index of sales,
# On the other hand, every year in February sales sink compared to January for almost every year of the time series.
# Moreover, in March, May and July the sales increase after declining for the months of April and June. Interesting
# also to notice that from August until the end of the year the sales increase following something similar to a linear trend.
```


```{r, fig.align='center'}
ts %>% autoplot(food_bev_tobacco_retail)
```


```{r, fig.align='center'}
# Classical decomposition
# Classical decomposition additive
ts %>% 
  model(classical_decomposition(food_bev_tobacco_retail, type = "additive")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
# Classical decomposition multiplicative
ts %>%
  model(classical_decomposition(food_bev_tobacco_retail, type = "multiplicative")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
```

```{r, fig.align='center'}
# Let's check the seasonality:
ts %>% gg_season(food_bev_tobacco_retail)
```

```{r, fig.align='center'}
ts %>% autoplot(`non-food_without_service_stations`)
```

```{r, fig.align='center'}
# Classical decomposition
# Classical decomposition additive
ts %>% 
  model(classical_decomposition(`non-food_without_service_stations`, type = "additive")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
# Classical decomposition multiplicative
ts %>%
  model(classical_decomposition(`non-food_without_service_stations`, type = "multiplicative")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
```

```{r, fig.align='center'}
# Let's check the seasonality:
ts %>% gg_season(`non-food_without_service_stations`)
```


```{r, fig.align='center'}
ts %>% autoplot(information_communication_equipment)
```

```{r, fig.align='center'}
# Classical decomposition
# Classical decomposition additive
ts %>% 
  model(classical_decomposition(information_communication_equipment, type = "additive")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
# Classical decomposition multiplicative
ts %>%
  model(classical_decomposition(information_communication_equipment, type = "multiplicative")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
```

```{r, fig.align='center'}
# Let's check the seasonality:
ts %>% gg_season(information_communication_equipment)
```

```{r, fig.align='center'}
ts %>% autoplot(other_household_equipment)
```

```{r, fig.align='center'}
# Classical decomposition
# Classical decomposition additive
ts %>% 
  model(classical_decomposition(other_household_equipment, type = "additive")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
# Classical decomposition multiplicative
ts %>%
  model(classical_decomposition(other_household_equipment, type = "multiplicative")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
```

```{r, fig.align='center'}
# Let's check the seasonality:
ts %>% gg_season(other_household_equipment)
```

```{r, fig.align='center'}
ts %>% autoplot(cultural_recreation)
```

```{r, fig.align='center'}
# Classical decomposition
# Classical decomposition additive
ts %>% 
  model(classical_decomposition(cultural_recreation, type = "additive")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
# Classical decomposition multiplicative
ts %>%
  model(classical_decomposition(cultural_recreation, type = "multiplicative")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
```

```{r, fig.align='center'}
# Let's check the seasonality:
ts %>% gg_season(cultural_recreation)
```

```{r, fig.align='center'}
ts %>% autoplot(other_goods)
```

```{r, fig.align='center'}
# Classical decomposition
# Classical decomposition additive
ts %>% 
  model(classical_decomposition(other_goods, type = "additive")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
# Classical decomposition multiplicative
ts %>%
  model(classical_decomposition(other_goods, type = "multiplicative")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
```

```{r, fig.align='center'}
# Let's check the seasonality:
ts %>% gg_season(other_goods)
```

```{r, fig.align='center'}
ts %>% autoplot(`478:479`)
```

```{r, fig.align='center'}
# Classical decomposition
# Classical decomposition additive
ts %>% 
  model(classical_decomposition(`478:479`, type = "additive")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
# Classical decomposition multiplicative
ts %>%
  model(classical_decomposition(`478:479`, type = "multiplicative")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
```

```{r, fig.align='center'}
# Let's check the seasonality:
ts %>% gg_season(`478:479`)
```

```{r, fig.align='center'}
ts %>% autoplot(service_stations)
```

```{r, fig.align='center'}
# Classical decomposition
# Classical decomposition additive
ts %>% 
  model(classical_decomposition(service_stations, type = "additive")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
# Classical decomposition multiplicative
ts %>%
  model(classical_decomposition(service_stations, type = "multiplicative")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
```

```{r, fig.align='center'}
# Let's check the seasonality:
ts %>% gg_season(service_stations)
```

```{r, fig.align='center'}
ts %>% autoplot(tot_without_fuel)
```

```{r, fig.align='center'}
# Classical decomposition
# Classical decomposition additive
ts %>% 
  model(classical_decomposition(tot_without_fuel, type = "additive")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
# Classical decomposition multiplicative
ts %>%
  model(classical_decomposition(tot_without_fuel, type = "multiplicative")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
```

```{r, fig.align='center'}
# Let's check the seasonality:
ts %>% gg_season(tot_without_fuel)
```

```{r, fig.align='center'}
ts %>% autoplot(clothing_footwear)
```

```{r, fig.align='center'}
# Classical decomposition
# Classical decomposition additive
ts %>% 
  model(classical_decomposition(clothing_footwear, type = "additive")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
# Classical decomposition multiplicative
ts %>%
  model(classical_decomposition(clothing_footwear, type = "multiplicative")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
```

```{r, fig.align='center'}
# Let's check the seasonality:
ts %>% gg_season(clothing_footwear)
```

```{r, fig.align='center'}
ts %>% autoplot(auto_fuel)
```

```{r, fig.align='center'}
# Classical decomposition
# Classical decomposition additive
ts %>% 
  model(classical_decomposition(auto_fuel, type = "additive")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
# Classical decomposition multiplicative
ts %>%
  model(classical_decomposition(auto_fuel, type = "multiplicative")) %>%
  components() %>%
  autoplot() +
  xlab("Years")
```

```{r, fig.align='center'}
# Let's check the seasonality:
ts %>% gg_season(auto_fuel)
```














## beginning of analysis

```{r, fig.align='center'}
# Exponential smoothing forecasting

fit_ETS <- ts %>%
  model(ETS(tot))

fit_ETS %>%
  report()

# The default function gives an ETS with multiplicative errors, additive trend with dampening and a multiplicative seasonality.

fit_ETS %>% forecast(h = 10) %>% autoplot(ts)
```

```{r, fig.align='center'}
# Let's apply an additive model
fit_ETS2 <- ts %>%
  model(ETS(tot ~ error("A") + trend("Ad")  + season("A")))

fit_ETS2 %>%
  report()

fit_ETS2 %>% forecast( h= 10) %>% autoplot(ts)

# Compare the accuracy between the 2 models:

accuracy(fit_ETS)
accuracy(fit_ETS2)

# The multiplicative model seems to be better.
```

```{r, fig.align='center'}
# Regression model with trend and season

fit_reg <- ts %>%
  model(TSLM(tot ~ trend() + season()))

report(fit_reg)

# Just to have a picture of the predictions and the actual data

augment(fit_reg) %>% ggplot(aes(x = year_month)) +
  geom_line(aes(y = tot, colour = "Data")) +
  geom_line(aes(y = .fitted, colour = "Fitted"))

# Check for the accuracy:

accuracy(fit_reg)

#It is not improved in relation with the previous ETS model.
```

```{r, fig.align='center'}
# As we know that the seasonality is probably slightly multiplicative log transfor the model

fit_regl <- ts %>%
  model(TSLM = TSLM(log(tot)~ trend() + season()))

augment(fit_regl)

tidy(fit_regl) %>% select(term, estimate)

expcoef <- (exp(coef(fit_regl)$estimate) - 1) * 100
options( scipen = 999)
expcoef

# Every month the sales increase by 7,2 %

fit_regl %>% forecast(h = 48) %>% autoplot(ts)

# compare reg model and log reg model:

accuracy(fit_regl)
accuracy(fit_reg)

# The reg model seems better.
```

```{r, fig.align='center'}
fit_arima <- ts %>% model(ARIMA(tot))
## A mable: 1 x 1
               #`ARIMA(tot)`
                   # <model>
#1 <ARIMA(2,1,2)(0,1,2)[12]>
accuracy(fit_arima)
forecast(fit_arima, h = 48) %>% autoplot(ts)
```

